# Generated by Django 4.2.5 on 2023-09-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ansyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('testarea', models.TextField()),
                ('option', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='gamedevelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='graphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='guie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='matlabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='pythone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='siemene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='solide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('result', models.TextField()),
                ('begen', models.IntegerField(auto_created=0)),
            ],
        ),
        migrations.CreateModel(
            name='gamedevelopslavee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.IntegerField()),
                ('ansys1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.ansyse')),
                ('gamedev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.gamedevelope')),
                ('graph1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.graphe')),
                ('gui1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.guie')),
                ('matlab1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.matlabe')),
                ('python1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.pythone')),
                ('siemen1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.siemene')),
                ('solid1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ilkim.solide')),
            ],
        ),
    ]
