# Generated by Django 4.2.5 on 2023-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansyse',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='ansyse',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='ansyse',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='ansyse',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='ansyse',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='gamedevelope',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='gamedevelope',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='gamedevelope',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='gamedevelope',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='gamedevelope',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='graphe',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='graphe',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='graphe',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='graphe',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='graphe',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='guie',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='guie',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='guie',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='guie',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='guie',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='matlabe',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='matlabe',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='matlabe',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='matlabe',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='matlabe',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='pythone',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='pythone',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='pythone',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='pythone',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='pythone',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='siemene',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='siemene',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='siemene',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='siemene',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='siemene',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='solide',
            name='img',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='solide',
            name='img1',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='solide',
            name='img2',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='solide',
            name='img3',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='solide',
            name='img4',
            field=models.ImageField(default='static/arkaplan.jpg', upload_to='static/images'),
        ),
    ]
