from django.db import models
class Form(models.Model):
    name=models.CharField(max_length=80)
    surname = models.CharField(max_length=80)
    email=models.EmailField()
    date=models.DateField()
    testarea=models.TextField()
    option = models.CharField(max_length=80)
    def __str__(self):
        return f"{self.name} {self.surname}"
class solide(models.Model):
    img = models.ImageField(upload_to="static/images", default="/static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    title=models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date=models.DateField()
    result=models.TextField()
    begen=models.IntegerField(auto_created=0)

    slug=models.SlugField(max_length=50,unique=True,null=True)
    def __str__(self):
        return f"{self.title} {self.date}"
class siemene(models.Model):
    img = models.ImageField(upload_to="static/images",default="static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images",default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images",default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images",default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images",default="static/images/arkaplan.jpg")
    title=models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date=models.DateField()
    result=models.TextField()
    begen=models.IntegerField(auto_created=0)

    slug=models.SlugField(max_length=50,unique=True,null=True)
    def __str__(self):
        return f"{self.title} {self.date}"
class matlabe(models.Model):
    img = models.ImageField(upload_to="static/images", default="websitedeneme/static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default=" websitedeneme/static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="websitedeneme/static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="websitedeneme/static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="websitedeneme/static/images/arkaplan.jpg")
    title = models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date = models.DateField()
    code=models.TextField()
    result=models.TextField()
    begen = models.IntegerField(auto_created=0)

    slug=models.SlugField(max_length=50,unique=True,null=True)
class pythone(models.Model):
    img = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    title = models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date = models.DateField()
    code = models.TextField()
    result = models.TextField()
    begen = models.IntegerField(auto_created=0)

    slug=models.SlugField(max_length=50,unique=True,null=True)
class guie(models.Model):
    img = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    title = models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date = models.DateField()
    code = models.TextField()
    result = models.TextField()
    begen = models.IntegerField(auto_created=0)

    slug=models.SlugField(max_length=50,unique=True,null=True)
class ansyse(models.Model):
    img = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    title = models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date = models.DateField()
    result = models.TextField()
    begen = models.IntegerField(auto_created=0)

    slug=models.SlugField(max_length=50,unique=True,null=True)
class gamedevelope(models.Model):
    img = models.ImageField(upload_to="static/images", default="websitedenem/static/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    title = models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date = models.DateField()
    code = models.TextField()
    result = models.TextField()
    begen = models.IntegerField(auto_created=0)
    slug=models.SlugField(max_length=50,unique=True,null=True)
class graphe(models.Model):
    img = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img1 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img2 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img3 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    img4 = models.ImageField(upload_to="static/images", default="static/images/arkaplan.jpg")
    title = models.CharField(max_length=80)
    goal = models.CharField(max_length=80)
    date = models.DateField()
    code = models.TextField()
    result = models.TextField()
    begen = models.IntegerField(auto_created=0)
    slug=models.SlugField(max_length=50,unique=True,null=True)
class gamedevelopslavee(models.Model):
    ide=models.IntegerField()
    gamedev=models.ForeignKey(gamedevelope,null=True,on_delete=models.DO_NOTHING, blank=True)
    matlab1 = models.ForeignKey(matlabe, null=True, on_delete=models.DO_NOTHING, blank=True)
    python1=models.ForeignKey(pythone, null=True, on_delete=models.DO_NOTHING, blank=True)
    gui1=models.ForeignKey(guie, null=True, on_delete=models.DO_NOTHING, blank=True)
    solid1=models.ForeignKey(solide, null=True, on_delete=models.DO_NOTHING, blank=True)
    siemen1 = models.ForeignKey(siemene, null=True, on_delete=models.DO_NOTHING, blank=True)
    graph1=  models.ForeignKey(graphe, null=True, on_delete=models.DO_NOTHING, blank=True)
    ansys1= models.ForeignKey(ansyse, null=True, on_delete=models.DO_NOTHING, blank=True)
    slug=models.SlugField(max_length=50,unique=True,null=True)